#!/bin/bash


list_bundles() {
    echo "loopswitch4.lv2"
}

if [ "x${1}x" == "x-lx" ]; then
    list_bundles
    exit 0
fi

if [ "x${LV2_PATH}x" == "xx" ]; then
    LV2_PATH=~/.lv2/
fi

# cd sooperlooper
make
make INSTALL_PATH=$LV2_PATH install
cd ..
